"""
Video compensation module for audio-visual synchronization
Applies micro speed adjustments to video segments when audio timing requires compensation
"""
import os
import json
import subprocess
from pathlib import Path
from typing import List, Dict
from rich.console import Console
from core.utils import *

console = Console()

COMPENSATION_FILE = 'output/audio/video_compensation.json'
COMPENSATED_VIDEO = 'output/video_compensated.mp4'
MAX_SPEED_CHANGE = 0.08  # Maximum 8% speed change (almost imperceptible)


def load_compensation_requests() -> List[Dict]:
    """Load video compensation requests generated by audio processing"""
    if not os.path.exists(COMPENSATION_FILE):
        return []
    
    with open(COMPENSATION_FILE, 'r', encoding='utf-8') as f:
        return json.load(f)


def calculate_optimal_speed(compensation_time: float, original_duration: float) -> float:
    """
    Calculate optimal video speed to absorb timing difference
    Constraints: 0.92 <= speed <= 1.08 (imperceptible to human eye)
    
    When audio is longer than video target duration, we need to SLOW DOWN video
    to match the longer audio duration.
    
    Example:
    - Original video duration: 10s
    - Audio duration: 12s (compensation_time = 2s)
    - Required speed = 10/12 = 0.83x (video plays slower, lasts longer)
    """
    if compensation_time <= 0:
        return 1.0
    
    # When audio is longer, video needs to SLOW DOWN
    # target_duration = original_duration + compensation_time
    # speed = original_duration / target_duration
    target_duration = original_duration + compensation_time
    required_speed = original_duration / target_duration
    
    # Clamp to acceptable range (0.92 to 1.0, video should not speed up)
    optimal_speed = max(1.0 - MAX_SPEED_CHANGE, min(1.0, required_speed))
    
    return optimal_speed


def apply_video_speedup(input_video: str, output_video: str, speed_factor: float, 
                       start_time: float, end_time: float) -> bool:
    """
    Apply speed adjustment to a video segment using FFmpeg with motion compensation
    Uses minterpolate for smooth frame interpolation
    """
    try:
        # Calculate target FPS to maintain smooth motion
        # If speeding up, we need to interpolate frames
        original_fps = 30  # Assume 30fps, could detect from video
        
        if speed_factor < 1.0:
            # Slow down: use setpts to make video last longer
            # setpts=PTS/speed_factor: when speed_factor=0.83, PTS/0.83=PTS*1.2, video slows down
            filter_chain = (
                f"[0:v]trim=start={start_time}:end={end_time},setpts=PTS-STARTPTS,"
                f"setpts=PTS/{speed_factor}[v];"
                f"[0:a]atrim=start={start_time}:end={end_time},asetpts=PTS-STARTPTS,"
                f"atempo={speed_factor}[a]"
            )
        elif abs(speed_factor - 1.0) < 0.001:
            # No speed change needed for this segment
            return True
        else:
            # Speed up (should not happen with current logic, but handle anyway)
            filter_chain = (
                f"[0:v]trim=start={start_time}:end={end_time},setpts=PTS-STARTPTS,"
                f"setpts=PTS/{speed_factor}[v];"
                f"[0:a]atrim=start={start_time}:end={end_time},asetpts=PTS-STARTPTS,"
                f"atempo={speed_factor}[a]"
            )
        
        cmd = [
            'ffmpeg', '-y',
            '-i', input_video,
            '-filter_complex', filter_chain,
            '-map', '[v]', '-map', '[a]',
            '-c:v', 'libx264', '-preset', 'medium', '-crf', '18',
            '-c:a', 'aac', '-b:a', '128k',
            '-avoid_negative_ts', 'make_zero',
            output_video
        ]
        
        console.print(f"[cyan]🎬 Applying video speed {speed_factor:.3f}x to segment {start_time:.2f}-{end_time:.2f}[/cyan]")
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            console.print(f"[yellow]⚠️ Video compensation failed: {result.stderr[:200]}[/yellow]")
            return False
        
        return True
        
    except Exception as e:
        console.print(f"[yellow]⚠️ Video compensation error: {e}[/yellow]")
        return False


def compensate_video_timing(input_video: str, output_video: str = None) -> str:
    """
    Main function to apply video compensation based on audio timing requirements
    
    Args:
        input_video: Path to input video file
        output_video: Path for output (optional, defaults to COMPENSATED_VIDEO)
    
    Returns:
        Path to compensated video file
    """
    if output_video is None:
        output_video = COMPENSATED_VIDEO
    
    # Load compensation requests
    compensation_requests = load_compensation_requests()
    
    if not compensation_requests:
        console.print("[green]✅ No video compensation needed[/green]")
        # Just copy the video if no compensation needed
        if input_video != output_video:
            subprocess.run(['cp', input_video, output_video], check=True)
        return input_video
    
    console.print(f"[bold blue]🎬 Applying video compensation for {len(compensation_requests)} segments...[/bold blue]")
    
    # If only one compensation request, process directly
    if len(compensation_requests) == 1:
        req = compensation_requests[0]
        speed = calculate_optimal_speed(req['compensation_time'], 
                                       req['chunk_end_time'] - req['chunk_start_time'])
        
        if speed >= 0.99:  # Almost no change needed
            console.print("[green]✅ Video speed change too small, skipping compensation[/green]")
            if input_video != output_video:
                subprocess.run(['cp', input_video, output_video], check=True)
            return output_video
        
        # Apply speed to entire video (simpler case)
        return apply_speed_to_full_video(input_video, output_video, speed)
    
    # Multiple segments: use segment-based processing
    return apply_segmented_compensation(input_video, output_video, compensation_requests)


def apply_speed_to_full_video(input_video: str, output_video: str, speed_factor: float) -> str:
    """Apply uniform speed change to entire video"""
    try:
        # When speed_factor < 1, we SLOW DOWN the video to match longer audio
        # setpts=PTS/speed_factor: when speed_factor=0.9, PTS/0.9=PTS*1.11, video slows down
        # atempo=speed_factor: when speed_factor=0.9, audio slows down to match
        cmd = [
            'ffmpeg', '-y',
            '-i', input_video,
            '-filter:v', f"setpts=PTS/{speed_factor}",
            '-filter:a', f"atempo={speed_factor}",
            '-c:v', 'libx264', '-preset', 'medium', '-crf', '18',
            '-c:a', 'aac', '-b:a', '128k',
            output_video
        ]

        console.print(f"[cyan]🎬 Applying uniform video speed {speed_factor:.3f}x (slowing down)[/cyan]")
        subprocess.run(cmd, check=True, capture_output=True)
        
        console.print(f"[bold green]✅ Video compensation complete: {output_video}[/bold green]")
        return output_video
        
    except subprocess.CalledProcessError as e:
        console.print(f"[yellow]⚠️ Full video speed change failed: {e}[/yellow]")
        # Fallback: copy original
        subprocess.run(['cp', input_video, output_video], check=True)
        return output_video


def apply_segmented_compensation(input_video: str, output_video: str, 
                                 compensation_requests: List[Dict]) -> str:
    """
    Apply different speed factors to different video segments
    This is more complex but allows finer control
    """
    console.print("[bold yellow]⚠️ Multiple compensation segments detected - using segment-based processing[/bold yellow]")
    
    # For simplicity in minimum-change version, we'll apply the average speed
    # A more advanced version could concatenate segments with different speeds
    
    avg_speed = sum(calculate_optimal_speed(
        req['compensation_time'],
        req['chunk_end_time'] - req['chunk_start_time']
    ) for req in compensation_requests) / len(compensation_requests)
    
    return apply_speed_to_full_video(input_video, output_video, avg_speed)


def cleanup_compensation_file():
    """Remove compensation file after processing"""
    if os.path.exists(COMPENSATION_FILE):
        os.remove(COMPENSATION_FILE)
        console.print("[cyan]🗑️ Cleaned up compensation file[/cyan]")


if __name__ == "__main__":
    # Test function
    import sys
    if len(sys.argv) > 1:
        input_vid = sys.argv[1]
        result = compensate_video_timing(input_vid)
        print(f"Compensated video: {result}")
    else:
        print("Usage: python _12_5_video_compensate.py <input_video>")
